/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Defines PolicySubjectMatchType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PolicySubjectMatchType
    {
        /// <summary>
        /// Enum CUSTOMATTRIBUTE for value: CUSTOM_ATTRIBUTE
        /// </summary>
        [EnumMember(Value = "CUSTOM_ATTRIBUTE")]
        CUSTOMATTRIBUTE = 1,

        /// <summary>
        /// Enum EMAIL for value: EMAIL
        /// </summary>
        [EnumMember(Value = "EMAIL")]
        EMAIL = 2,

        /// <summary>
        /// Enum USERNAME for value: USERNAME
        /// </summary>
        [EnumMember(Value = "USERNAME")]
        USERNAME = 3,

        /// <summary>
        /// Enum USERNAMEOREMAIL for value: USERNAME_OR_EMAIL
        /// </summary>
        [EnumMember(Value = "USERNAME_OR_EMAIL")]
        USERNAMEOREMAIL = 4

    }

}
