/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Release channel for auto-update
    /// </summary>
    /// <value>Release channel for auto-update</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReleaseChannel
    {
        /// <summary>
        /// Enum BETA for value: BETA
        /// </summary>
        [EnumMember(Value = "BETA")]
        BETA = 1,

        /// <summary>
        /// Enum EA for value: EA
        /// </summary>
        [EnumMember(Value = "EA")]
        EA = 2,

        /// <summary>
        /// Enum GA for value: GA
        /// </summary>
        [EnumMember(Value = "GA")]
        GA = 3,

        /// <summary>
        /// Enum TEST for value: TEST
        /// </summary>
        [EnumMember(Value = "TEST")]
        TEST = 4

    }

}
