/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AutoLoginApplicationSettingsAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutoLoginApplicationSettingsAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutoLoginApplicationSettingsAllOf
        //private AutoLoginApplicationSettingsAllOf instance;

        public AutoLoginApplicationSettingsAllOfTests()
        {
            // TODO uncomment below to create an instance of AutoLoginApplicationSettingsAllOf
            //instance = new AutoLoginApplicationSettingsAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutoLoginApplicationSettingsAllOf
        /// </summary>
        [Fact]
        public void AutoLoginApplicationSettingsAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutoLoginApplicationSettingsAllOf
            //Assert.IsType<AutoLoginApplicationSettingsAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'SignOn'
        /// </summary>
        [Fact]
        public void SignOnTest()
        {
            // TODO unit test for the property 'SignOn'
        }

    }

}
