/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Error
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Error
        //private Error instance;

        public ErrorTests()
        {
            // TODO uncomment below to create an instance of Error
            //instance = new Error();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Error
        /// </summary>
        [Fact]
        public void ErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" Error
            //Assert.IsType<Error>(instance);
        }


        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorSummary'
        /// </summary>
        [Fact]
        public void ErrorSummaryTest()
        {
            // TODO unit test for the property 'ErrorSummary'
        }
        /// <summary>
        /// Test the property 'ErrorLink'
        /// </summary>
        [Fact]
        public void ErrorLinkTest()
        {
            // TODO unit test for the property 'ErrorLink'
        }
        /// <summary>
        /// Test the property 'ErrorId'
        /// </summary>
        [Fact]
        public void ErrorIdTest()
        {
            // TODO unit test for the property 'ErrorId'
        }
        /// <summary>
        /// Test the property 'ErrorCauses'
        /// </summary>
        [Fact]
        public void ErrorCausesTest()
        {
            // TODO unit test for the property 'ErrorCauses'
        }

    }

}
