/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LogCredentialProvider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogCredentialProviderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogCredentialProvider
        //private LogCredentialProvider instance;

        public LogCredentialProviderTests()
        {
            // TODO uncomment below to create an instance of LogCredentialProvider
            //instance = new LogCredentialProvider();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogCredentialProvider
        /// </summary>
        [Fact]
        public void LogCredentialProviderInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogCredentialProvider
            //Assert.IsType<LogCredentialProvider>(instance);
        }



    }

}
