/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LogSecurityContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogSecurityContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogSecurityContext
        //private LogSecurityContext instance;

        public LogSecurityContextTests()
        {
            // TODO uncomment below to create an instance of LogSecurityContext
            //instance = new LogSecurityContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogSecurityContext
        /// </summary>
        [Fact]
        public void LogSecurityContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogSecurityContext
            //Assert.IsType<LogSecurityContext>(instance);
        }


        /// <summary>
        /// Test the property 'AsNumber'
        /// </summary>
        [Fact]
        public void AsNumberTest()
        {
            // TODO unit test for the property 'AsNumber'
        }
        /// <summary>
        /// Test the property 'AsOrg'
        /// </summary>
        [Fact]
        public void AsOrgTest()
        {
            // TODO unit test for the property 'AsOrg'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'IsProxy'
        /// </summary>
        [Fact]
        public void IsProxyTest()
        {
            // TODO unit test for the property 'IsProxy'
        }
        /// <summary>
        /// Test the property 'Isp'
        /// </summary>
        [Fact]
        public void IspTest()
        {
            // TODO unit test for the property 'Isp'
        }

    }

}
