/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OAuth2ScopeMetadataPublish
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuth2ScopeMetadataPublishTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuth2ScopeMetadataPublish
        //private OAuth2ScopeMetadataPublish instance;

        public OAuth2ScopeMetadataPublishTests()
        {
            // TODO uncomment below to create an instance of OAuth2ScopeMetadataPublish
            //instance = new OAuth2ScopeMetadataPublish();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuth2ScopeMetadataPublish
        /// </summary>
        [Fact]
        public void OAuth2ScopeMetadataPublishInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuth2ScopeMetadataPublish
            //Assert.IsType<OAuth2ScopeMetadataPublish>(instance);
        }



    }

}
