/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PasswordPolicySettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PasswordPolicySettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PasswordPolicySettings
        //private PasswordPolicySettings instance;

        public PasswordPolicySettingsTests()
        {
            // TODO uncomment below to create an instance of PasswordPolicySettings
            //instance = new PasswordPolicySettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PasswordPolicySettings
        /// </summary>
        [Fact]
        public void PasswordPolicySettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PasswordPolicySettings
            //Assert.IsType<PasswordPolicySettings>(instance);
        }


        /// <summary>
        /// Test the property 'Delegation'
        /// </summary>
        [Fact]
        public void DelegationTest()
        {
            // TODO unit test for the property 'Delegation'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Recovery'
        /// </summary>
        [Fact]
        public void RecoveryTest()
        {
            // TODO unit test for the property 'Recovery'
        }

    }

}
