/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PushUserFactorProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushUserFactorProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushUserFactorProfile
        //private PushUserFactorProfile instance;

        public PushUserFactorProfileTests()
        {
            // TODO uncomment below to create an instance of PushUserFactorProfile
            //instance = new PushUserFactorProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushUserFactorProfile
        /// </summary>
        [Fact]
        public void PushUserFactorProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" PushUserFactorProfile
            //Assert.IsType<PushUserFactorProfile>(instance);
        }


        /// <summary>
        /// Test the property 'CredentialId'
        /// </summary>
        [Fact]
        public void CredentialIdTest()
        {
            // TODO unit test for the property 'CredentialId'
        }
        /// <summary>
        /// Test the property 'DeviceToken'
        /// </summary>
        [Fact]
        public void DeviceTokenTest()
        {
            // TODO unit test for the property 'DeviceToken'
        }
        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Fact]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }

    }

}
