/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SchemeApplicationCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchemeApplicationCredentialsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchemeApplicationCredentials
        //private SchemeApplicationCredentials instance;

        public SchemeApplicationCredentialsTests()
        {
            // TODO uncomment below to create an instance of SchemeApplicationCredentials
            //instance = new SchemeApplicationCredentials();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchemeApplicationCredentials
        /// </summary>
        [Fact]
        public void SchemeApplicationCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchemeApplicationCredentials
            //Assert.IsType<SchemeApplicationCredentials>(instance);
        }


        /// <summary>
        /// Test the property 'Signing'
        /// </summary>
        [Fact]
        public void SigningTest()
        {
            // TODO unit test for the property 'Signing'
        }
        /// <summary>
        /// Test the property 'UserNameTemplate'
        /// </summary>
        [Fact]
        public void UserNameTemplateTest()
        {
            // TODO unit test for the property 'UserNameTemplate'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'RevealPassword'
        /// </summary>
        [Fact]
        public void RevealPasswordTest()
        {
            // TODO unit test for the property 'RevealPassword'
        }
        /// <summary>
        /// Test the property 'Scheme'
        /// </summary>
        [Fact]
        public void SchemeTest()
        {
            // TODO unit test for the property 'Scheme'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
