/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserLifecycleAttributePolicyRuleCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserLifecycleAttributePolicyRuleConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserLifecycleAttributePolicyRuleCondition
        //private UserLifecycleAttributePolicyRuleCondition instance;

        public UserLifecycleAttributePolicyRuleConditionTests()
        {
            // TODO uncomment below to create an instance of UserLifecycleAttributePolicyRuleCondition
            //instance = new UserLifecycleAttributePolicyRuleCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserLifecycleAttributePolicyRuleCondition
        /// </summary>
        [Fact]
        public void UserLifecycleAttributePolicyRuleConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserLifecycleAttributePolicyRuleCondition
            //Assert.IsType<UserLifecycleAttributePolicyRuleCondition>(instance);
        }


        /// <summary>
        /// Test the property 'AttributeName'
        /// </summary>
        [Fact]
        public void AttributeNameTest()
        {
            // TODO unit test for the property 'AttributeName'
        }
        /// <summary>
        /// Test the property 'MatchingValue'
        /// </summary>
        [Fact]
        public void MatchingValueTest()
        {
            // TODO unit test for the property 'MatchingValue'
        }

    }

}
