/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing NetworkZoneApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NetworkZoneApiTests : IDisposable
    {
        private NetworkZoneApi instance;

        public NetworkZoneApiTests()
        {
            instance = new NetworkZoneApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkZoneApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NetworkZoneApi
            //Assert.IsType<NetworkZoneApi>(instance);
        }

        /// <summary>
        /// Test ActivateNetworkZone
        /// </summary>
        [Fact]
        public void ActivateNetworkZoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string zoneId = null;
            //var response = instance.ActivateNetworkZone(zoneId);
            //Assert.IsType<NetworkZone>(response);
        }

        /// <summary>
        /// Test CreateNetworkZone
        /// </summary>
        [Fact]
        public void CreateNetworkZoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NetworkZone zone = null;
            //var response = instance.CreateNetworkZone(zone);
            //Assert.IsType<NetworkZone>(response);
        }

        /// <summary>
        /// Test DeactivateNetworkZone
        /// </summary>
        [Fact]
        public void DeactivateNetworkZoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string zoneId = null;
            //var response = instance.DeactivateNetworkZone(zoneId);
            //Assert.IsType<NetworkZone>(response);
        }

        /// <summary>
        /// Test DeleteNetworkZone
        /// </summary>
        [Fact]
        public void DeleteNetworkZoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string zoneId = null;
            //instance.DeleteNetworkZone(zoneId);
        }

        /// <summary>
        /// Test GetNetworkZone
        /// </summary>
        [Fact]
        public void GetNetworkZoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string zoneId = null;
            //var response = instance.GetNetworkZone(zoneId);
            //Assert.IsType<NetworkZone>(response);
        }

        /// <summary>
        /// Test ListNetworkZones
        /// </summary>
        [Fact]
        public void ListNetworkZonesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string after = null;
            //int? limit = null;
            //string filter = null;
            //var response = instance.ListNetworkZones(after, limit, filter);
            //Assert.IsType<List<NetworkZone>>(response);
        }

        /// <summary>
        /// Test UpdateNetworkZone
        /// </summary>
        [Fact]
        public void UpdateNetworkZoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string zoneId = null;
            //NetworkZone zone = null;
            //var response = instance.UpdateNetworkZone(zoneId, zone);
            //Assert.IsType<NetworkZone>(response);
        }
    }
}
