/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 2024.07.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Settings specific to the Okta Admin Console
    /// </summary>
    [DataContract(Name = "AdminConsoleSettings")]
    
    public partial class AdminConsoleSettings : IEquatable<AdminConsoleSettings>
    {
        
        /// <summary>
        /// The maximum idle time before the Okta Admin Console session expires. Must be no more than 12 hours.
        /// </summary>
        /// <value>The maximum idle time before the Okta Admin Console session expires. Must be no more than 12 hours.</value>
        [DataMember(Name = "sessionIdleTimeoutMinutes", EmitDefaultValue = true)]
        public int SessionIdleTimeoutMinutes { get; set; }

        /// <summary>
        /// The absolute maximum session lifetime of the Okta Admin Console. Must be no more than 7 days.
        /// </summary>
        /// <value>The absolute maximum session lifetime of the Okta Admin Console. Must be no more than 7 days.</value>
        [DataMember(Name = "sessionMaxLifetimeMinutes", EmitDefaultValue = true)]
        public int SessionMaxLifetimeMinutes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdminConsoleSettings {\n");
            sb.Append("  SessionIdleTimeoutMinutes: ").Append(SessionIdleTimeoutMinutes).Append("\n");
            sb.Append("  SessionMaxLifetimeMinutes: ").Append(SessionMaxLifetimeMinutes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AdminConsoleSettings);
        }

        /// <summary>
        /// Returns true if AdminConsoleSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of AdminConsoleSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdminConsoleSettings input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SessionIdleTimeoutMinutes == input.SessionIdleTimeoutMinutes ||
                    this.SessionIdleTimeoutMinutes.Equals(input.SessionIdleTimeoutMinutes)
                ) && 
                (
                    this.SessionMaxLifetimeMinutes == input.SessionMaxLifetimeMinutes ||
                    this.SessionMaxLifetimeMinutes.Equals(input.SessionMaxLifetimeMinutes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                hashCode = (hashCode * 59) + this.SessionIdleTimeoutMinutes.GetHashCode();
                hashCode = (hashCode * 59) + this.SessionMaxLifetimeMinutes.GetHashCode();
                return hashCode;
            }
        }

    }

}
