/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// ApplicationLayoutsLinks
    /// </summary>
    [DataContract(Name = "ApplicationLayouts__links")]
    
    public partial class ApplicationLayoutsLinks : IEquatable<ApplicationLayoutsLinks>
    {
        
        /// <summary>
        /// Gets or Sets General
        /// </summary>
        [DataMember(Name = "general", EmitDefaultValue = true)]
        public List<HrefObject> General { get; set; }

        /// <summary>
        /// Gets or Sets SignOn
        /// </summary>
        [DataMember(Name = "signOn", EmitDefaultValue = true)]
        public List<HrefObject> SignOn { get; set; }

        /// <summary>
        /// Gets or Sets Provisioning
        /// </summary>
        [DataMember(Name = "provisioning", EmitDefaultValue = true)]
        public List<HrefObject> Provisioning { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplicationLayoutsLinks {\n");
            sb.Append("  General: ").Append(General).Append("\n");
            sb.Append("  SignOn: ").Append(SignOn).Append("\n");
            sb.Append("  Provisioning: ").Append(Provisioning).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApplicationLayoutsLinks);
        }

        /// <summary>
        /// Returns true if ApplicationLayoutsLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of ApplicationLayoutsLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicationLayoutsLinks input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.General == input.General ||
                    this.General != null &&
                    input.General != null &&
                    this.General.SequenceEqual(input.General)
                ) && 
                (
                    this.SignOn == input.SignOn ||
                    this.SignOn != null &&
                    input.SignOn != null &&
                    this.SignOn.SequenceEqual(input.SignOn)
                ) && 
                (
                    this.Provisioning == input.Provisioning ||
                    this.Provisioning != null &&
                    input.Provisioning != null &&
                    this.Provisioning.SequenceEqual(input.Provisioning)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.General != null)
                {
                    hashCode = (hashCode * 59) + this.General.GetHashCode();
                }
                if (this.SignOn != null)
                {
                    hashCode = (hashCode * 59) + this.SignOn.GetHashCode();
                }
                if (this.Provisioning != null)
                {
                    hashCode = (hashCode * 59) + this.Provisioning.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
