/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// AuthenticatorMethodBase
    /// </summary>
    [DataContract(Name = "AuthenticatorMethodBase")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodOtp), "AuthenticatorMethodOtp")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodPush), "AuthenticatorMethodPush")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSignedNonce), "AuthenticatorMethodSignedNonce")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSimple), "AuthenticatorMethodSimple")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodTotp), "AuthenticatorMethodTotp")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodWebAuthn), "AuthenticatorMethodWebAuthn")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodWithVerifiableProperties), "AuthenticatorMethodWithVerifiableProperties")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodWithVerifiableProperties), "cert")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodWithVerifiableProperties), "duo")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSimple), "email")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodWithVerifiableProperties), "idp")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodOtp), "otp")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSimple), "password")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodPush), "push")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSimple), "security_question")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSignedNonce), "signed_nonce")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSimple), "sms")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodTotp), "totp")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodSimple), "voice")]
    [JsonSubtypes.KnownSubType(typeof(AuthenticatorMethodWebAuthn), "webauthn")]
    
    public partial class AuthenticatorMethodBase : IEquatable<AuthenticatorMethodBase>
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        
        public LifecycleStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        
        public AuthenticatorMethodType Type { get; set; }
        
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "_links", EmitDefaultValue = true)]
        public LinksSelfAndLifecycle Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthenticatorMethodBase {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthenticatorMethodBase);
        }

        /// <summary>
        /// Returns true if AuthenticatorMethodBase instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthenticatorMethodBase to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthenticatorMethodBase input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
