/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// BeforeScheduledActionPolicyRuleCondition
    /// </summary>
    [DataContract(Name = "BeforeScheduledActionPolicyRuleCondition")]
    
    public partial class BeforeScheduledActionPolicyRuleCondition : IEquatable<BeforeScheduledActionPolicyRuleCondition>
    {
        
        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public Duration Duration { get; set; }

        /// <summary>
        /// Gets or Sets LifecycleAction
        /// </summary>
        [DataMember(Name = "lifecycleAction", EmitDefaultValue = true)]
        public ScheduledUserLifecycleAction LifecycleAction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BeforeScheduledActionPolicyRuleCondition {\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  LifecycleAction: ").Append(LifecycleAction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BeforeScheduledActionPolicyRuleCondition);
        }

        /// <summary>
        /// Returns true if BeforeScheduledActionPolicyRuleCondition instances are equal
        /// </summary>
        /// <param name="input">Instance of BeforeScheduledActionPolicyRuleCondition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BeforeScheduledActionPolicyRuleCondition input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Duration == input.Duration ||
                    (this.Duration != null &&
                    this.Duration.Equals(input.Duration))
                ) && 
                (
                    this.LifecycleAction == input.LifecycleAction ||
                    (this.LifecycleAction != null &&
                    this.LifecycleAction.Equals(input.LifecycleAction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Duration != null)
                {
                    hashCode = (hashCode * 59) + this.Duration.GetHashCode();
                }
                if (this.LifecycleAction != null)
                {
                    hashCode = (hashCode * 59) + this.LifecycleAction.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
