/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Current credential sync status of the privileged resource
    /// </summary>
    /// <value>Current credential sync status of the privileged resource</value>
    [JsonConverter(typeof(StringEnumSerializingConverter))]
    public sealed class CredentialSyncState : StringEnum
    {
        /// <summary>
        /// StringEnum CredentialSyncState for value: NOT_SYNCED
        /// </summary>
        public static CredentialSyncState NOTSYNCED = new CredentialSyncState("NOT_SYNCED");
        /// <summary>
        /// StringEnum CredentialSyncState for value: SYNCED
        /// </summary>
        public static CredentialSyncState SYNCED = new CredentialSyncState("SYNCED");
        /// <summary>
        /// StringEnum CredentialSyncState for value: SYNCING
        /// </summary>
        public static CredentialSyncState SYNCING = new CredentialSyncState("SYNCING");
        /// <summary>
        /// StringEnum CredentialSyncState for value: SYNC_FAILED
        /// </summary>
        public static CredentialSyncState SYNCFAILED = new CredentialSyncState("SYNC_FAILED");

        /// <summary>
        /// Implicit operator declaration to accept and convert a string value as a <see cref="CredentialSyncState"/>
        /// </summary>
        /// <param name="value">The value to use</param>
        public static implicit operator CredentialSyncState(string value) => new CredentialSyncState(value);

        /// <summary>
        /// Creates a new <see cref="CredentialSyncState"/> instance.
        /// </summary>
        /// <param name="value">The value to use.</param>
        public CredentialSyncState(string value)
            : base(value)
        {
        }
    }


}
