/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Settings for third-party signal providers (based on the &#x60;ANDROID&#x60; platform)
    /// </summary>
    [DataContract(Name = "DeviceAssuranceAndroidPlatform_allOf_thirdPartySignalProviders")]
    
    public partial class DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders : IEquatable<DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders>
    {
        
        /// <summary>
        /// Gets or Sets AndroidDeviceTrust
        /// </summary>
        [DataMember(Name = "androidDeviceTrust", EmitDefaultValue = true)]
        public AndroidDeviceTrust AndroidDeviceTrust { get; set; }

        /// <summary>
        /// Gets or Sets DevicePostureIdP
        /// </summary>
        [DataMember(Name = "devicePostureIdP", EmitDefaultValue = true)]
        public DevicePostureIdP DevicePostureIdP { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders {\n");
            sb.Append("  AndroidDeviceTrust: ").Append(AndroidDeviceTrust).Append("\n");
            sb.Append("  DevicePostureIdP: ").Append(DevicePostureIdP).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders);
        }

        /// <summary>
        /// Returns true if DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders instances are equal
        /// </summary>
        /// <param name="input">Instance of DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeviceAssuranceAndroidPlatformAllOfThirdPartySignalProviders input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AndroidDeviceTrust == input.AndroidDeviceTrust ||
                    (this.AndroidDeviceTrust != null &&
                    this.AndroidDeviceTrust.Equals(input.AndroidDeviceTrust))
                ) && 
                (
                    this.DevicePostureIdP == input.DevicePostureIdP ||
                    (this.DevicePostureIdP != null &&
                    this.DevicePostureIdP.Equals(input.DevicePostureIdP))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.AndroidDeviceTrust != null)
                {
                    hashCode = (hashCode * 59) + this.AndroidDeviceTrust.GetHashCode();
                }
                if (this.DevicePostureIdP != null)
                {
                    hashCode = (hashCode * 59) + this.DevicePostureIdP.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
