/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// The grant type
    /// </summary>
    /// <value>The grant type</value>
    [JsonConverter(typeof(StringEnumSerializingConverter))]
    public sealed class GovernanceSourceType : StringEnum
    {
        /// <summary>
        /// StringEnum GovernanceSourceType for value: CUSTOM
        /// </summary>
        public static GovernanceSourceType CUSTOM = new GovernanceSourceType("CUSTOM");
        /// <summary>
        /// StringEnum GovernanceSourceType for value: ENTITLEMENT-BUNDLE
        /// </summary>
        public static GovernanceSourceType ENTITLEMENTBUNDLE = new GovernanceSourceType("ENTITLEMENT-BUNDLE");

        /// <summary>
        /// Implicit operator declaration to accept and convert a string value as a <see cref="GovernanceSourceType"/>
        /// </summary>
        /// <param name="value">The value to use</param>
        public static implicit operator GovernanceSourceType(string value) => new GovernanceSourceType(value);

        /// <summary>
        /// Creates a new <see cref="GovernanceSourceType"/> instance.
        /// </summary>
        /// <param name="value">The value to use.</param>
        public GovernanceSourceType(string value)
            : base(value)
        {
        }
    }


}
