/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Discoverable resources related to the group push mapping
    /// </summary>
    [DataContract(Name = "GroupPushMappingLinks")]
    
    public partial class GroupPushMappingLinks : IEquatable<GroupPushMappingLinks>
    {
        
        /// <summary>
        /// Gets or Sets App
        /// </summary>
        [DataMember(Name = "app", EmitDefaultValue = true)]
        public HrefObjectAppLink App { get; set; }

        /// <summary>
        /// Gets or Sets SourceGroup
        /// </summary>
        [DataMember(Name = "sourceGroup", EmitDefaultValue = true)]
        public HrefObjectGroupLink SourceGroup { get; set; }

        /// <summary>
        /// Gets or Sets TargetGroup
        /// </summary>
        [DataMember(Name = "targetGroup", EmitDefaultValue = true)]
        public HrefObjectGroupLink TargetGroup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GroupPushMappingLinks {\n");
            sb.Append("  App: ").Append(App).Append("\n");
            sb.Append("  SourceGroup: ").Append(SourceGroup).Append("\n");
            sb.Append("  TargetGroup: ").Append(TargetGroup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GroupPushMappingLinks);
        }

        /// <summary>
        /// Returns true if GroupPushMappingLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of GroupPushMappingLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GroupPushMappingLinks input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.App == input.App ||
                    (this.App != null &&
                    this.App.Equals(input.App))
                ) && 
                (
                    this.SourceGroup == input.SourceGroup ||
                    (this.SourceGroup != null &&
                    this.SourceGroup.Equals(input.SourceGroup))
                ) && 
                (
                    this.TargetGroup == input.TargetGroup ||
                    (this.TargetGroup != null &&
                    this.TargetGroup.Equals(input.TargetGroup))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.App != null)
                {
                    hashCode = (hashCode * 59) + this.App.GetHashCode();
                }
                if (this.SourceGroup != null)
                {
                    hashCode = (hashCode * 59) + this.SourceGroup.GetHashCode();
                }
                if (this.TargetGroup != null)
                {
                    hashCode = (hashCode * 59) + this.TargetGroup.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
