// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Determines the Okta username for the imported user
    /// </summary>
    [DataContract(Name = "ImportUsernameObject")]
    
    public partial class ImportUsernameObject : IEquatable<ImportUsernameObject>
    {
        /// <summary>
        /// Determines the username format when users sign in to Okta
        /// </summary>
        /// <value>Determines the username format when users sign in to Okta</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class UsernameFormatEnum : StringEnum
        {
            /// <summary>
            /// StringEnum EMAIL for value: EMAIL
            /// </summary>
            
            public static UsernameFormatEnum EMAIL = new UsernameFormatEnum("EMAIL");

            /// <summary>
            /// StringEnum CUSTOM for value: CUSTOM
            /// </summary>
            
            public static UsernameFormatEnum CUSTOM = new UsernameFormatEnum("CUSTOM");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="UsernameFormatEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator UsernameFormatEnum(string value) => new UsernameFormatEnum(value);

            /// <summary>
            /// Creates a new <see cref="UsernameFormat"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public UsernameFormatEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Determines the username format when users sign in to Okta
        /// </summary>
        /// <value>Determines the username format when users sign in to Okta</value>
        [DataMember(Name = "usernameFormat", EmitDefaultValue = true)]
        
        public UsernameFormatEnum UsernameFormat { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportUsernameObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public ImportUsernameObject() { }
        
        /// <summary>
        /// For &#x60;usernameFormat&#x3D;CUSTOM&#x60;, specifies the Okta Expression Language statement for a username format that imported users use to sign in to Okta
        /// </summary>
        /// <value>For &#x60;usernameFormat&#x3D;CUSTOM&#x60;, specifies the Okta Expression Language statement for a username format that imported users use to sign in to Okta</value>
        [DataMember(Name = "userNameExpression", EmitDefaultValue = true)]
        public string UserNameExpression { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportUsernameObject {\n");
            sb.Append("  UserNameExpression: ").Append(UserNameExpression).Append("\n");
            sb.Append("  UsernameFormat: ").Append(UsernameFormat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImportUsernameObject);
        }

        /// <summary>
        /// Returns true if ImportUsernameObject instances are equal
        /// </summary>
        /// <param name="input">Instance of ImportUsernameObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImportUsernameObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.UserNameExpression == input.UserNameExpression ||
                    (this.UserNameExpression != null &&
                    this.UserNameExpression.Equals(input.UserNameExpression))
                ) && 
                (
                    this.UsernameFormat == input.UsernameFormat ||
                    this.UsernameFormat.Equals(input.UsernameFormat)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.UserNameExpression != null)
                {
                    hashCode = (hashCode * 59) + this.UserNameExpression.GetHashCode();
                }
                if (this.UsernameFormat != null)
                {
                    hashCode = (hashCode * 59) + this.UsernameFormat.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
