/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Patch request object for Cross App Access Connections
    /// </summary>
    [DataContract(Name = "OrgCrossAppAccessConnectionPatchRequest")]
    
    public partial class OrgCrossAppAccessConnectionPatchRequest : IEquatable<OrgCrossAppAccessConnectionPatchRequest>
    {
        /// <summary>
        /// Requested value of Cross App Access connection status
        /// </summary>
        /// <value>Requested value of Cross App Access connection status</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class StatusEnum : StringEnum
        {
            /// <summary>
            /// StringEnum ACTIVE for value: ACTIVE
            /// </summary>
            
            public static StatusEnum ACTIVE = new StatusEnum("ACTIVE");

            /// <summary>
            /// StringEnum INACTIVE for value: INACTIVE
            /// </summary>
            
            public static StatusEnum INACTIVE = new StatusEnum("INACTIVE");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="StatusEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator StatusEnum(string value) => new StatusEnum(value);

            /// <summary>
            /// Creates a new <see cref="Status"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public StatusEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Requested value of Cross App Access connection status
        /// </summary>
        /// <value>Requested value of Cross App Access connection status</value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrgCrossAppAccessConnectionPatchRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public OrgCrossAppAccessConnectionPatchRequest() { }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrgCrossAppAccessConnectionPatchRequest {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrgCrossAppAccessConnectionPatchRequest);
        }

        /// <summary>
        /// Returns true if OrgCrossAppAccessConnectionPatchRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of OrgCrossAppAccessConnectionPatchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrgCrossAppAccessConnectionPatchRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
