// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Connection object for Cross App Access connections
    /// </summary>
    [DataContract(Name = "OrgCrossAppAccessConnection")]
    
    public partial class OrgCrossAppAccessConnection : IEquatable<OrgCrossAppAccessConnection>
    {
        /// <summary>
        /// Indicates if the Cross App Access connection is active or inactive
        /// </summary>
        /// <value>Indicates if the Cross App Access connection is active or inactive</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class StatusEnum : StringEnum
        {
            /// <summary>
            /// StringEnum ACTIVE for value: ACTIVE
            /// </summary>
            
            public static StatusEnum ACTIVE = new StatusEnum("ACTIVE");

            /// <summary>
            /// StringEnum INACTIVE for value: INACTIVE
            /// </summary>
            
            public static StatusEnum INACTIVE = new StatusEnum("INACTIVE");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="StatusEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator StatusEnum(string value) => new StatusEnum(value);

            /// <summary>
            /// Creates a new <see cref="Status"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public StatusEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Indicates if the Cross App Access connection is active or inactive
        /// </summary>
        /// <value>Indicates if the Cross App Access connection is active or inactive</value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        
        public StatusEnum Status { get; set; }
        
        /// <summary>
        /// The ISO 8601 formatted date and time when the connection was created
        /// </summary>
        /// <value>The ISO 8601 formatted date and time when the connection was created</value>
        [DataMember(Name = "created", EmitDefaultValue = true)]
        public DateTimeOffset Created { get; private set; }

        /// <summary>
        /// Returns false as Created should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreated()
        {
            return false;
        }
        /// <summary>
        /// Unique identifier for the connection
        /// </summary>
        /// <value>Unique identifier for the connection</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; private set; }

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return false;
        }
        /// <summary>
        /// The ISO 8601 formatted date and time when the connection was last updated
        /// </summary>
        /// <value>The ISO 8601 formatted date and time when the connection was last updated</value>
        [DataMember(Name = "lastUpdated", EmitDefaultValue = true)]
        public DateTimeOffset LastUpdated { get; private set; }

        /// <summary>
        /// Returns false as LastUpdated should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeLastUpdated()
        {
            return false;
        }
        /// <summary>
        /// ID of the requesting app instance
        /// </summary>
        /// <value>ID of the requesting app instance</value>
        [DataMember(Name = "requestingAppInstanceId", EmitDefaultValue = true)]
        public string RequestingAppInstanceId { get; set; }

        /// <summary>
        /// ID of the resource app instance
        /// </summary>
        /// <value>ID of the resource app instance</value>
        [DataMember(Name = "resourceAppInstanceId", EmitDefaultValue = true)]
        public string ResourceAppInstanceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrgCrossAppAccessConnection {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("  RequestingAppInstanceId: ").Append(RequestingAppInstanceId).Append("\n");
            sb.Append("  ResourceAppInstanceId: ").Append(ResourceAppInstanceId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrgCrossAppAccessConnection);
        }

        /// <summary>
        /// Returns true if OrgCrossAppAccessConnection instances are equal
        /// </summary>
        /// <param name="input">Instance of OrgCrossAppAccessConnection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrgCrossAppAccessConnection input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LastUpdated == input.LastUpdated ||
                    (this.LastUpdated != null &&
                    this.LastUpdated.Equals(input.LastUpdated))
                ) && 
                (
                    this.RequestingAppInstanceId == input.RequestingAppInstanceId ||
                    (this.RequestingAppInstanceId != null &&
                    this.RequestingAppInstanceId.Equals(input.RequestingAppInstanceId))
                ) && 
                (
                    this.ResourceAppInstanceId == input.ResourceAppInstanceId ||
                    (this.ResourceAppInstanceId != null &&
                    this.ResourceAppInstanceId.Equals(input.ResourceAppInstanceId))
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Created != null)
                {
                    hashCode = (hashCode * 59) + this.Created.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.LastUpdated != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdated.GetHashCode();
                }
                if (this.RequestingAppInstanceId != null)
                {
                    hashCode = (hashCode * 59) + this.RequestingAppInstanceId.GetHashCode();
                }
                if (this.ResourceAppInstanceId != null)
                {
                    hashCode = (hashCode * 59) + this.ResourceAppInstanceId.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
