// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Specifies link relations (see [Web Linking](https://www.rfc-editor.org/rfc/rfc8288)) available for the org using the [JSON Hypertext Application Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06) specification
    /// </summary>
    [DataContract(Name = "orgGeneralSettingLinks")]
    
    public partial class OrgGeneralSettingLinks : IEquatable<OrgGeneralSettingLinks>
    {
        
        /// <summary>
        /// Gets or Sets Contacts
        /// </summary>
        [DataMember(Name = "contacts", EmitDefaultValue = true)]
        public OrgGeneralSettingLinksContacts Contacts { get; set; }

        /// <summary>
        /// Gets or Sets Logo
        /// </summary>
        [DataMember(Name = "logo", EmitDefaultValue = true)]
        public OrgGeneralSettingLinksLogo Logo { get; set; }

        /// <summary>
        /// Gets or Sets OktaCommunication
        /// </summary>
        [DataMember(Name = "oktaCommunication", EmitDefaultValue = true)]
        public OrgGeneralSettingLinksOktaCommunication OktaCommunication { get; set; }

        /// <summary>
        /// Gets or Sets OktaSupport
        /// </summary>
        [DataMember(Name = "oktaSupport", EmitDefaultValue = true)]
        public OrgGeneralSettingLinksOktaSupport OktaSupport { get; set; }

        /// <summary>
        /// Gets or Sets Preferences
        /// </summary>
        [DataMember(Name = "preferences", EmitDefaultValue = true)]
        public OrgGeneralSettingLinksPreferences Preferences { get; set; }

        /// <summary>
        /// Gets or Sets UploadLogo
        /// </summary>
        [DataMember(Name = "uploadLogo", EmitDefaultValue = true)]
        public OrgGeneralSettingLinksUploadLogo UploadLogo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrgGeneralSettingLinks {\n");
            sb.Append("  Contacts: ").Append(Contacts).Append("\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("  OktaCommunication: ").Append(OktaCommunication).Append("\n");
            sb.Append("  OktaSupport: ").Append(OktaSupport).Append("\n");
            sb.Append("  Preferences: ").Append(Preferences).Append("\n");
            sb.Append("  UploadLogo: ").Append(UploadLogo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrgGeneralSettingLinks);
        }

        /// <summary>
        /// Returns true if OrgGeneralSettingLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of OrgGeneralSettingLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrgGeneralSettingLinks input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Contacts == input.Contacts ||
                    (this.Contacts != null &&
                    this.Contacts.Equals(input.Contacts))
                ) && 
                (
                    this.Logo == input.Logo ||
                    (this.Logo != null &&
                    this.Logo.Equals(input.Logo))
                ) && 
                (
                    this.OktaCommunication == input.OktaCommunication ||
                    (this.OktaCommunication != null &&
                    this.OktaCommunication.Equals(input.OktaCommunication))
                ) && 
                (
                    this.OktaSupport == input.OktaSupport ||
                    (this.OktaSupport != null &&
                    this.OktaSupport.Equals(input.OktaSupport))
                ) && 
                (
                    this.Preferences == input.Preferences ||
                    (this.Preferences != null &&
                    this.Preferences.Equals(input.Preferences))
                ) && 
                (
                    this.UploadLogo == input.UploadLogo ||
                    (this.UploadLogo != null &&
                    this.UploadLogo.Equals(input.UploadLogo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Contacts != null)
                {
                    hashCode = (hashCode * 59) + this.Contacts.GetHashCode();
                }
                if (this.Logo != null)
                {
                    hashCode = (hashCode * 59) + this.Logo.GetHashCode();
                }
                if (this.OktaCommunication != null)
                {
                    hashCode = (hashCode * 59) + this.OktaCommunication.GetHashCode();
                }
                if (this.OktaSupport != null)
                {
                    hashCode = (hashCode * 59) + this.OktaSupport.GetHashCode();
                }
                if (this.Preferences != null)
                {
                    hashCode = (hashCode * 59) + this.Preferences.GetHashCode();
                }
                if (this.UploadLogo != null)
                {
                    hashCode = (hashCode * 59) + this.UploadLogo.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
