/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 2024.07.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Defines ProvisioningAction
    /// </summary>
    [JsonConverter(typeof(StringEnumSerializingConverter))]
    public sealed class ProvisioningAction : StringEnum
    {
        /// <summary>
        /// StringEnum ProvisioningAction for value: AUTO
        /// </summary>
        public static ProvisioningAction AUTO = new ProvisioningAction("AUTO");
        /// <summary>
        /// StringEnum ProvisioningAction for value: CALLOUT
        /// </summary>
        public static ProvisioningAction CALLOUT = new ProvisioningAction("CALLOUT");
        /// <summary>
        /// StringEnum ProvisioningAction for value: DISABLED
        /// </summary>
        public static ProvisioningAction DISABLED = new ProvisioningAction("DISABLED");

        /// <summary>
        /// Implicit operator declaration to accept and convert a string value as a <see cref="ProvisioningAction"/>
        /// </summary>
        /// <param name="value">The value to use</param>
        public static implicit operator ProvisioningAction(string value) => new ProvisioningAction(value);

        /// <summary>
        /// Creates a new <see cref="ProvisioningAction"/> instance.
        /// </summary>
        /// <param name="value">The value to use.</param>
        public ProvisioningAction(string value)
            : base(value)
        {
        }
    }


}
