// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// SAMLHookResponse
    /// </summary>
    [DataContract(Name = "SAMLHookResponse")]
    
    public partial class SAMLHookResponse : IEquatable<SAMLHookResponse>
    {
        
        /// <summary>
        /// The &#x60;commands&#x60; object is where you tell Okta to add additional claims to the assertion or to modify the existing assertion statements.  &#x60;commands&#x60; is an array, allowing you to send multiple commands. In each array element, include a &#x60;type&#x60; property and a &#x60;value&#x60; property. The &#x60;type&#x60; property is where you specify which of the supported commands you want to execute, and &#x60;value&#x60; is where you supply an operand for that command. In the case of the SAML assertion inline hook, the &#x60;value&#x60; property is itself a nested object, in which you specify a particular operation, a path to act on, and a value.
        /// </summary>
        /// <value>The &#x60;commands&#x60; object is where you tell Okta to add additional claims to the assertion or to modify the existing assertion statements.  &#x60;commands&#x60; is an array, allowing you to send multiple commands. In each array element, include a &#x60;type&#x60; property and a &#x60;value&#x60; property. The &#x60;type&#x60; property is where you specify which of the supported commands you want to execute, and &#x60;value&#x60; is where you supply an operand for that command. In the case of the SAML assertion inline hook, the &#x60;value&#x60; property is itself a nested object, in which you specify a particular operation, a path to act on, and a value.</value>
        [DataMember(Name = "commands", EmitDefaultValue = true)]
        public List<SAMLHookResponseCommandsInner> Commands { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public SAMLHookResponseError Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SAMLHookResponse {\n");
            sb.Append("  Commands: ").Append(Commands).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SAMLHookResponse);
        }

        /// <summary>
        /// Returns true if SAMLHookResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SAMLHookResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SAMLHookResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Commands == input.Commands ||
                    this.Commands != null &&
                    input.Commands != null &&
                    this.Commands.SequenceEqual(input.Commands)
                ) && 
                (
                    this.Error == input.Error ||
                    (this.Error != null &&
                    this.Error.Equals(input.Error))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.Commands != null)
                {
                    hashCode = (hashCode * 59) + this.Commands.GetHashCode();
                }
                if (this.Error != null)
                {
                    hashCode = (hashCode * 59) + this.Error.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
