// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Provides a JSON representation of the &#x60;&lt;saml:Conditions&gt;&#x60; element of the SAML assertion
    /// </summary>
    [DataContract(Name = "SAMLPayLoad_data_assertion_conditions")]
    
    public partial class SAMLPayLoadDataAssertionConditions : IEquatable<SAMLPayLoadDataAssertionConditions>
    {
        
        /// <summary>
        /// Describes which service providers the assertion is valid for
        /// </summary>
        /// <value>Describes which service providers the assertion is valid for</value>
        [DataMember(Name = "audienceRestriction", EmitDefaultValue = true)]
        public List<string> AudienceRestriction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SAMLPayLoadDataAssertionConditions {\n");
            sb.Append("  AudienceRestriction: ").Append(AudienceRestriction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SAMLPayLoadDataAssertionConditions);
        }

        /// <summary>
        /// Returns true if SAMLPayLoadDataAssertionConditions instances are equal
        /// </summary>
        /// <param name="input">Instance of SAMLPayLoadDataAssertionConditions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SAMLPayLoadDataAssertionConditions input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AudienceRestriction == input.AudienceRestriction ||
                    this.AudienceRestriction != null &&
                    input.AudienceRestriction != null &&
                    this.AudienceRestriction.SequenceEqual(input.AudienceRestriction)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.AudienceRestriction != null)
                {
                    hashCode = (hashCode * 59) + this.AudienceRestriction.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
