/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// Details for managing an Okta user as a service account
    /// </summary>
    [DataContract(Name = "ServiceAccountDetailsOktaUserAccount")]
    [JsonConverter(typeof(JsonSubtypes), "AccountType")]
    [JsonSubtypes.KnownSubType(typeof(ServiceAccountDetailsAppAccount), "APP_ACCOUNT")]
    [JsonSubtypes.KnownSubType(typeof(ServiceAccountDetailsOktaUserAccount), "OKTA_USER_ACCOUNT")]
    
    public partial class ServiceAccountDetailsOktaUserAccount : ServiceAccount, IEquatable<ServiceAccountDetailsOktaUserAccount>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceAccountDetailsOktaUserAccount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public ServiceAccountDetailsOktaUserAccount() { }
        
        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [DataMember(Name = "details", EmitDefaultValue = true)]
        public ServiceAccountDetailsOktaUserAccountSub Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceAccountDetailsOktaUserAccount {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceAccountDetailsOktaUserAccount);
        }

        /// <summary>
        /// Returns true if ServiceAccountDetailsOktaUserAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceAccountDetailsOktaUserAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceAccountDetailsOktaUserAccount input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Details == input.Details ||
                    (this.Details != null &&
                    this.Details.Equals(input.Details))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                
                if (this.Details != null)
                {
                    hashCode = (hashCode * 59) + this.Details.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
