/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Defines ShowSignInWithOV
    /// </summary>
    [JsonConverter(typeof(StringEnumSerializingConverter))]
    public sealed class ShowSignInWithOV : StringEnum
    {
        /// <summary>
        /// StringEnum ShowSignInWithOV for value: ALWAYS
        /// </summary>
        public static ShowSignInWithOV ALWAYS = new ShowSignInWithOV("ALWAYS");
        /// <summary>
        /// StringEnum ShowSignInWithOV for value: NEVER
        /// </summary>
        public static ShowSignInWithOV NEVER = new ShowSignInWithOV("NEVER");

        /// <summary>
        /// Implicit operator declaration to accept and convert a string value as a <see cref="ShowSignInWithOV"/>
        /// </summary>
        /// <param name="value">The value to use</param>
        public static implicit operator ShowSignInWithOV(string value) => new ShowSignInWithOV(value);

        /// <summary>
        /// Creates a new <see cref="ShowSignInWithOV"/> instance.
        /// </summary>
        /// <param name="value">The value to use.</param>
        public ShowSignInWithOV(string value)
            : base(value)
        {
        }
    }


}
