// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Template: ModelGeneric
    /// UserFactorPushTransaction
    /// </summary>
    [DataContract(Name = "UserFactorPushTransaction")]
    [JsonConverter(typeof(JsonSubtypes), "FactorResult")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionRejected), "REJECTED")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransaction), "SUCCESS")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionTimeout), "TIMEOUT")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionRejected), "UserFactorPushTransactionRejected")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionTimeout), "UserFactorPushTransactionTimeout")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionWaitingNMC), "UserFactorPushTransactionWaitingNMC")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionWaitingNoNMC), "UserFactorPushTransactionWaitingNoNMC")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionWaitingNoNMC), "WAITING")]
    [JsonSubtypes.KnownSubType(typeof(UserFactorPushTransactionWaitingNMC), "WAITING (with number matching challenge)")]
    
    public partial class UserFactorPushTransaction : IEquatable<UserFactorPushTransaction>
    {
        /// <summary>
        /// Result of the verification transaction
        /// </summary>
        /// <value>Result of the verification transaction</value>
        [JsonConverter(typeof(StringEnumSerializingConverter))]
        public sealed class FactorResultEnum : StringEnum
        {
            /// <summary>
            /// StringEnum WAITINGwithNumberMatchingChallenge for value: WAITING (with number matching challenge)
            /// </summary>
            
            public static FactorResultEnum WAITINGwithNumberMatchingChallenge = new FactorResultEnum("WAITING (with number matching challenge)");

            /// <summary>
            /// StringEnum WAITING for value: WAITING
            /// </summary>
            
            public static FactorResultEnum WAITING = new FactorResultEnum("WAITING");

            /// <summary>
            /// StringEnum SUCCESS for value: SUCCESS
            /// </summary>
            
            public static FactorResultEnum SUCCESS = new FactorResultEnum("SUCCESS");

            /// <summary>
            /// StringEnum REJECTED for value: REJECTED
            /// </summary>
            
            public static FactorResultEnum REJECTED = new FactorResultEnum("REJECTED");

            /// <summary>
            /// StringEnum TIMEOUT for value: TIMEOUT
            /// </summary>
            
            public static FactorResultEnum TIMEOUT = new FactorResultEnum("TIMEOUT");


            /// <summary>
            /// Implicit operator declaration to accept and convert a string value as a <see cref="FactorResultEnum"/>
            /// </summary>
            /// <param name="value">The value to use</param>
            public static implicit operator FactorResultEnum(string value) => new FactorResultEnum(value);

            /// <summary>
            /// Creates a new <see cref="FactorResult"/> instance.
            /// </summary>
            /// <param name="value">The value to use.</param>
            public FactorResultEnum(string value)
                : base(value)
            {
            }
        }


        /// <summary>
        /// Result of the verification transaction
        /// </summary>
        /// <value>Result of the verification transaction</value>
        [DataMember(Name = "factorResult", EmitDefaultValue = true)]
        
        public FactorResultEnum FactorResult { get; set; }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserFactorPushTransaction {\n");
            sb.Append("  FactorResult: ").Append(FactorResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserFactorPushTransaction);
        }

        /// <summary>
        /// Returns true if UserFactorPushTransaction instances are equal
        /// </summary>
        /// <param name="input">Instance of UserFactorPushTransaction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserFactorPushTransaction input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FactorResult == input.FactorResult ||
                    this.FactorResult.Equals(input.FactorResult)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                
                if (this.FactorResult != null)
                {
                    hashCode = (hashCode * 59) + this.FactorResult.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
