// <copyright company="Okta, Inc">
// Copyright (c) 2014-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

/*
 * Okta Admin Management
 *
 * Allows customers to easily access the Okta Management APIs
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devex-public@okta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Okta.Sdk.Client.OpenAPIDateConverter;

namespace Okta.Sdk.Model
{
    /// <summary>
    /// Defines UserSchemaAttributeFormat
    /// </summary>
    [JsonConverter(typeof(StringEnumSerializingConverter))]
    public sealed class UserSchemaAttributeFormat : StringEnum
    {
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: country-code
        /// </summary>
        public static UserSchemaAttributeFormat CountryCode = new UserSchemaAttributeFormat("country-code");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: date-time
        /// </summary>
        public static UserSchemaAttributeFormat DateTime = new UserSchemaAttributeFormat("date-time");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: email
        /// </summary>
        public static UserSchemaAttributeFormat Email = new UserSchemaAttributeFormat("email");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: encrypted
        /// </summary>
        public static UserSchemaAttributeFormat Encrypted = new UserSchemaAttributeFormat("encrypted");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: hashed
        /// </summary>
        public static UserSchemaAttributeFormat Hashed = new UserSchemaAttributeFormat("hashed");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: language-code
        /// </summary>
        public static UserSchemaAttributeFormat LanguageCode = new UserSchemaAttributeFormat("language-code");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: locale
        /// </summary>
        public static UserSchemaAttributeFormat Locale = new UserSchemaAttributeFormat("locale");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: ref-id
        /// </summary>
        public static UserSchemaAttributeFormat RefId = new UserSchemaAttributeFormat("ref-id");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: timezone
        /// </summary>
        public static UserSchemaAttributeFormat Timezone = new UserSchemaAttributeFormat("timezone");
        /// <summary>
        /// StringEnum UserSchemaAttributeFormat for value: uri
        /// </summary>
        public static UserSchemaAttributeFormat Uri = new UserSchemaAttributeFormat("uri");

        /// <summary>
        /// Implicit operator declaration to accept and convert a string value as a <see cref="UserSchemaAttributeFormat"/>
        /// </summary>
        /// <param name="value">The value to use</param>
        public static implicit operator UserSchemaAttributeFormat(string value) => new UserSchemaAttributeFormat(value);

        /// <summary>
        /// Creates a new <see cref="UserSchemaAttributeFormat"/> instance.
        /// </summary>
        /// <param name="value">The value to use.</param>
        public UserSchemaAttributeFormat(string value)
            : base(value)
        {
        }
    }


}
