name: Regenerate Okta.Sdk

on: [push]

jobs:
  regenerate-sdk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install @okta/openapi
      working-directory: ./openapi
      run: npm install -g @okta/openapi
    
    - name: Npm install
      working-directory: ./openapi
      run: npm install

    - name: Run Unit Tests Before Sdk Regeneration
      working-directory: ./src/Okta.Sdk.UnitTests
      run: dotnet test

    - name: Regenerate Okta.Sdk
      working-directory: ./openapi
      run: npm run generate

    - name: Git Diff
      run: git diff
      
    - name: Run Unit Tests After Sdk Regeneration
      working-directory: ./src/Okta.Sdk.UnitTests
      run: |
        dotnet clean &&
        dotnet test
